# Generated by Django 5.2.5 on 2025-08-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_delete_configuracion_alter_usuario_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='level',
            field=models.CharField(choices=[('bronce', 'Bronce'), ('plata', 'Plata'), ('oro', 'Oro'), ('platino', 'Platino'), ('diamante', 'Diamante')], default='bronce', max_length=10),
        ),
    ]
