# Generated by Django 5.2.5 on 2025-08-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='puntos_juego',
            field=models.IntegerField(default=0),
        ),
    ]
