# Generated by Django 5.2.5 on 2025-08-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_usuario_puntos_juego'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='puntos_juego_vidrios',
            field=models.IntegerField(default=0),
        ),
    ]
