# Generated by Django 5.2.5 on 2025-08-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_usuario_puntos_juego_vidrios'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='puntos_juego_papel',
            field=models.IntegerField(default=0),
        ),
    ]
