# Generated by Django 5.2.5 on 2025-08-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_usuario_puntos_juego_papel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='puntos_juego_metales',
            field=models.IntegerField(default=0),
        ),
    ]
