# Generated by Django 5.2.5 on 2025-08-12 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_usuario_puntos_juego_metales'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('canje_pendiente', 'Canje Pendiente'), ('canje_aprobado', 'Canje Aprobado'), ('canje_rechazado', 'Canje Rechazado'), ('redencion_pendiente', 'Redención Pendiente'), ('redencion_aprobada', 'Redención Aprobada'), ('redencion_rechazada', 'Redención Rechazada'), ('recompensa_canjeada', 'Recompensa Canjeada'), ('sistema', 'Sistema')], default='sistema', max_length=30),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='titulo',
            field=models.CharField(default='Notificación', max_length=200),
        ),
    ]
