# Generated by Django 5.2.5 on 2025-08-12 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_notificacion_tipo_notificacion_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='level',
            field=models.CharField(choices=[('guardian_verde', 'Guardián Verde'), ('defensor_planeta', 'Defensor del Planeta'), ('heroe_eco', 'Héroe Eco'), ('embajador_ambiental', 'Embajador Ambiental'), ('leyenda_sustentable', 'Leyenda Sustentable')], default='guardian_verde', max_length=25),
        ),
    ]
