# Generated by Django 5.2.5 on 2025-08-12 05:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_usuario_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='recompensa',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoria'),
        ),
        migrations.AddField(
            model_name='recompensa',
            name='es_nuevo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recompensa',
            name='es_oferta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recompensa',
            name='es_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recompensa',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recompensa',
            name='fecha_vencimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recompensa',
            name='veces_canjeada',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='FavoritoRecompensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('recompensa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.recompensa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorito Recompensa',
                'verbose_name_plural': 'Favoritos Recompensas',
                'unique_together': {('usuario', 'recompensa')},
            },
        ),
    ]
