# Generated by Django 5.2.5 on 2025-08-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_recompensa_categoria_recompensa_es_nuevo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='suspended',
            field=models.BooleanField(default=False, help_text='Usuario suspendido permanentemente'),
        ),
    ]
