# Generated by Django 5.2.5 on 2025-08-31 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_configuracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fecha_aceptacion_terminos',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando aceptó los términos', null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='terminos_aceptados',
            field=models.BooleanField(default=False, help_text='Usuario ha aceptado los términos y condiciones'),
        ),
    ]
