# Generated by Django 5.2.5 on 2025-08-31 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_usuario_fecha_aceptacion_terminos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='canje',
            name='direccion_recoleccion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='canje',
            name='foto_material_inicial',
            field=models.ImageField(blank=True, null=True, upload_to='materiales_iniciales/'),
        ),
        migrations.AddField(
            model_name='canje',
            name='foto_material_recolectado',
            field=models.ImageField(blank=True, null=True, upload_to='materiales_recolectados/'),
        ),
        migrations.AddField(
            model_name='canje',
            name='horario_disponible',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='canje',
            name='necesita_recoleccion',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='canje',
            name='peso_real',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='canje',
            name='puntos_finales',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='canje',
            name='referencia_direccion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='canje',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='canje',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('recolectado', 'Recolectado'), ('verificando', 'Verificando'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('completado', 'Completado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('canje_pendiente', 'Canje Pendiente'), ('canje_aprobado', 'Canje Aprobado'), ('canje_rechazado', 'Canje Rechazado'), ('redencion_pendiente', 'Redención Pendiente'), ('redencion_aprobada', 'Redención Aprobada'), ('redencion_rechazada', 'Redención Rechazada'), ('recompensa_canjeada', 'Recompensa Canjeada'), ('retiro_enviado', 'Retiro Enviado'), ('perfil_actualizado', 'Perfil Actualizado'), ('password_cambiado', 'Contraseña Cambiada'), ('foto_actualizada', 'Foto Actualizada'), ('sistema', 'Sistema')], default='sistema', max_length=30),
        ),
        migrations.CreateModel(
            name='RutaRecoleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_programada', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin_estimada', models.TimeField()),
                ('zona', models.CharField(max_length=50)),
                ('vehiculo_tipo', models.CharField(choices=[('moto', 'Motocicleta'), ('camion_pequeno', 'Camión Pequeño'), ('camion_grande', 'Camión Grande')], default='camion_pequeno', max_length=20)),
                ('capacidad_maxima', models.DecimalField(decimal_places=2, default=100.0, max_digits=8)),
                ('estado', models.CharField(choices=[('planificada', 'Planificada'), ('programada', 'Programada'), ('en_curso', 'En Curso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='planificada', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio_real', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin_real', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('kilometros_recorridos', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('costo_combustible', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('conductor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas_conductor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='canje',
            name='ruta_asignada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.rutarecoleccion'),
        ),
        migrations.CreateModel(
            name='ParadaRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('direccion', models.CharField(max_length=255)),
                ('referencia', models.TextField(blank=True)),
                ('telefono_contacto', models.CharField(max_length=20)),
                ('horario_preferido', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_camino', 'En Camino'), ('llegada', 'Llegada'), ('recolectando', 'Recolectando'), ('completada', 'Completada'), ('no_encontrado', 'No Encontrado'), ('reagendada', 'Reagendada')], default='pendiente', max_length=20)),
                ('hora_llegada_estimada', models.TimeField(blank=True, null=True)),
                ('hora_llegada_real', models.DateTimeField(blank=True, null=True)),
                ('hora_salida_real', models.DateTimeField(blank=True, null=True)),
                ('peso_recolectado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('foto_antes', models.ImageField(blank=True, null=True, upload_to='paradas/antes/')),
                ('foto_despues', models.ImageField(blank=True, null=True, upload_to='paradas/despues/')),
                ('canje', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parada', to='core.canje')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='core.rutarecoleccion')),
            ],
            options={
                'ordering': ['orden'],
                'unique_together': {('ruta', 'orden')},
            },
        ),
    ]
