# Generated by Django 5.2.5 on 2025-09-01 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_canje_direccion_recoleccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canje',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('recolectado', 'Recolectado'), ('verificando', 'Verificando'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('completado', 'Completado'), ('pendiente_recoleccion', 'Pendiente Recolección'), ('en_recoleccion', 'En Recolección')], default='pendiente', max_length=25),
        ),
    ]
