# Generated by Django 5.2.5 on 2025-09-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_fix_estado_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superusuario'), ('admin', 'Administrador'), ('user', 'Usuario Regular')], default='user', max_length=10),
        ),
    ]
