# Generated by Django 5.2.5 on 2025-09-18 22:46
# Generated by Django 5.2 on 2025-09-19 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_fix_estado_max_length'),
        ('core', '0034_alter_usuario_role'),
        ('core', '0034_chatmessage'),
    ]

    operations = [
    ]
