# Generated by Django 5.2.5 on 2025-10-10 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_usuario_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoRecompensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_seguimiento', models.CharField(max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('solicitado', 'Solicitado'), ('confirmado', 'Confirmado'), ('preparando', 'Preparando Pedido'), ('empacado', 'Empacado'), ('en_transito', 'En Tránsito'), ('en_reparto', 'En Reparto'), ('entregado', 'Entregado'), ('problema', 'Problema en Entrega'), ('cancelado', 'Cancelado')], default='solicitado', max_length=20)),
                ('direccion_entrega', models.TextField()),
                ('telefono_contacto', models.CharField(max_length=20)),
                ('fecha_estimada_entrega', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega_real', models.DateTimeField(blank=True, null=True)),
                ('notas_adicionales', models.TextField(blank=True)),
                ('foto_entrega', models.ImageField(blank=True, null=True, upload_to='entregas/')),
                ('calificacion_servicio', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('recompensa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='core.recompensa')),
                ('redencion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seguimiento', to='core.redencionpuntos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos_recompensa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seguimiento de Recompensa',
                'verbose_name_plural': 'Seguimientos de Recompensas',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='HistorialSeguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, choices=[('solicitado', 'Solicitado'), ('confirmado', 'Confirmado'), ('preparando', 'Preparando Pedido'), ('empacado', 'Empacado'), ('en_transito', 'En Tránsito'), ('en_reparto', 'En Reparto'), ('entregado', 'Entregado'), ('problema', 'Problema en Entrega'), ('cancelado', 'Cancelado')], max_length=20, null=True)),
                ('estado_nuevo', models.CharField(choices=[('solicitado', 'Solicitado'), ('confirmado', 'Confirmado'), ('preparando', 'Preparando Pedido'), ('empacado', 'Empacado'), ('en_transito', 'En Tránsito'), ('en_reparto', 'En Reparto'), ('entregado', 'Entregado'), ('problema', 'Problema en Entrega'), ('cancelado', 'Cancelado')], max_length=20)),
                ('comentario', models.TextField(blank=True)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('usuario_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('seguimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='core.seguimientorecompensa')),
            ],
            options={
                'verbose_name': 'Historial de Seguimiento',
                'verbose_name_plural': 'Historiales de Seguimiento',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
