# Generated by Django 5.2.5 on 2025-10-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_seguimientorecompensa_historialseguimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='codigo_verificacion',
            field=models.CharField(blank=True, help_text='Código de verificación 2FA', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='codigo_verificacion_expira',
            field=models.DateTimeField(blank=True, help_text='Expiración del código 2FA', null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='email_verificado',
            field=models.BooleanField(default=False, help_text='Email verificado con código 2FA'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='intentos_verificacion',
            field=models.IntegerField(default=0, help_text='Intentos fallidos de verificación'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='verificacion_bloqueada_hasta',
            field=models.DateTimeField(blank=True, help_text='Bloqueo temporal por intentos fallidos', null=True),
        ),
    ]
