# Generated by Django 5.2 on 2025-10-23 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_add_2fa_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superusuario'), ('admin', 'Administrador'), ('conductor', 'Conductor'), ('user', 'Usuario Regular')], default='user', max_length=10),
        ),
    ]
