# Generated by Django 4.2.7 on 2025-11-13 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_usuario_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversacionChatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('finalizada', 'Finalizada'), ('escalada', 'Escalada a Humano'), ('pausada', 'Pausada')], default='activa', max_length=20)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('escalado_a_humano', models.BooleanField(default=False)),
                ('total_mensajes', models.IntegerField(default=0)),
                ('promedio_confianza', models.FloatField(blank=True, null=True)),
                ('temas_identificados', models.JSONField(blank=True, default=list)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_chatbot', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversación Chatbot',
                'verbose_name_plural': 'Conversaciones Chatbot',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='EstadisticasChatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('total_conversaciones', models.IntegerField(default=0)),
                ('conversaciones_exitosas', models.IntegerField(default=0)),
                ('conversaciones_escaladas', models.IntegerField(default=0)),
                ('total_mensajes_usuario', models.IntegerField(default=0)),
                ('total_mensajes_ia', models.IntegerField(default=0)),
                ('tiempo_respuesta_promedio', models.FloatField(default=0.0)),
                ('confianza_promedio', models.FloatField(default=0.0)),
                ('tokens_utilizados', models.IntegerField(default=0)),
                ('satisfaccion_promedio', models.FloatField(blank=True, null=True)),
                ('porcentaje_escalamiento', models.FloatField(default=0.0)),
                ('temas_frecuentes', models.JSONField(blank=True, default=dict)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estadísticas Chatbot',
                'verbose_name_plural': 'Estadísticas Chatbot',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AlterField(
            model_name='redencionpuntos',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='SolicitudSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MensajeChatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('es_usuario', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('intent_detected', models.CharField(blank=True, max_length=100)),
                ('entities_extracted', models.JSONField(blank=True, default=dict)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('ai_model_used', models.CharField(blank=True, max_length=50)),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='core.conversacionchatbot')),
            ],
            options={
                'verbose_name': 'Mensaje Chatbot',
                'verbose_name_plural': 'Mensajes Chatbot',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ContextoChatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos_usuario', models.JSONField(blank=True, default=dict)),
                ('temas_discutidos', models.JSONField(blank=True, default=list)),
                ('problemas_identificados', models.JSONField(blank=True, default=list)),
                ('soluciones_propuestas', models.JSONField(blank=True, default=list)),
                ('sentimiento_usuario', models.CharField(blank=True, max_length=20)),
                ('nivel_frustacion', models.IntegerField(default=0)),
                ('satisfaccion_estimada', models.IntegerField(blank=True, null=True)),
                ('requiere_escalamiento', models.BooleanField(default=False)),
                ('motivo_escalamiento', models.CharField(blank=True, max_length=200)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('conversacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contexto', to='core.conversacionchatbot')),
            ],
            options={
                'verbose_name': 'Contexto Chatbot',
                'verbose_name_plural': 'Contextos Chatbot',
            },
        ),
    ]
