# Generated by Django 5.2.5 on 2025-10-23 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_usuario_role'),
        ('core', '0040_chatbot_models'),
    ]

    operations = [
    ]
