# Generated by Django 4.2.7 on 2025-11-13 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_conversacionchatbot_estadisticaschatbot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversacionDirecta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('pausada', 'Pausada'), ('finalizada', 'Finalizada')], default='activa', max_length=20)),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('fecha_ultima_actividad', models.DateTimeField(auto_now=True)),
                ('total_mensajes', models.IntegerField(default=0)),
                ('satisfaccion_usuario', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('notas_admin', models.TextField(blank=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversación Directa',
                'verbose_name_plural': 'Conversaciones Directas',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.AddField(
            model_name='solicitudsoporte',
            name='admin_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitudsoporte',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('en_chat', 'En Chat'), ('finalizada', 'Finalizada')], default='pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='MensajeDirecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
                ('es_admin', models.BooleanField()),
                ('editado', models.BooleanField(default=False)),
                ('fecha_edicion', models.DateTimeField(blank=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='core.conversaciondirecta')),
            ],
            options={
                'verbose_name': 'Mensaje Directo',
                'verbose_name_plural': 'Mensajes Directos',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddField(
            model_name='conversaciondirecta',
            name='solicitud_soporte',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversacion_directa', to='core.solicitudsoporte'),
        ),
        migrations.AddField(
            model_name='conversaciondirecta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
