# Generated by Django 5.2.5 on 2025-10-23 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_merge_0040_alter_usuario_role_0040_chatbot_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacionchatbot',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
