# Generated by Django 5.2.5 on 2025-10-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_conversacionchatbot_fecha_actualizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redencionpuntos',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
    ]
