# Generated by Django 4.2.7 on 2025-11-13 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_agregar_estado_aprobado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensajechat',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='mensajechat',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='mensajeticket',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='mensajeticket',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='ticketsoporte',
            name='asignado_a',
        ),
        migrations.RemoveField(
            model_name='ticketsoporte',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='conversacionchatbot',
            name='ticket_relacionado',
        ),
        migrations.DeleteModel(
            name='ChatSoporte',
        ),
        migrations.DeleteModel(
            name='MensajeChat',
        ),
        migrations.DeleteModel(
            name='MensajeTicket',
        ),
        migrations.DeleteModel(
            name='TicketSoporte',
        ),
    ]
